[project]
name = "gerilife-caregiving"
version = "0.1.0"
description = "Caregiving visualization tool to promote wellness in elder-care communities."
authors = ["Brylie Christopher Oxley <brylie@protonmail.com>"]
license = "EUPL-1.2"
readme = "README.md"
