# Generated by Django 4.2.7 on 2023-11-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("outdoor", "Outdoor"),
                            ("culture", "Culture"),
                            ("discussion", "Discussion"),
                            ("self_guided", "Self-guided"),
                        ],
                        default="self_guided",
                        max_length=20,
                        verbose_name="Activity type",
                    ),
                ),
                ("date", models.DateField(verbose_name="Activity date")),
                (
                    "duration_m",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Duration in minutes"
                    ),
                ),
                (
                    "residents",
                    models.ManyToManyField(
                        related_name="activities", to="residents.resident"
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "db_table": "activity",
                "ordering": ["-date"],
            },
        ),
    ]
