# Generated by Django 4.2.7 on 2023-11-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="duration_m",
            new_name="duration_minutes",
        ),
    ]
