# Generated by Django 4.2.8 on 2023-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_caregiver_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('outdoor', 'Outdoor'), ('casual_social', 'Casual Social'), ('culture', 'Culture'), ('discussion', 'Discussion'), ('guided', 'Guided'), ('music', 'Music'), ('self_guided', 'Self-guided'), ('trip', 'Trip')], default='self_guided', max_length=20, verbose_name='Activity type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='caregiver_role',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('hobby_instructor', 'Hobby Instructor'), ('nurse', 'Nurse'), ('physio_therapist', 'Physio therapist'), ('practical_nurse', 'Practical nurse'), ('volunteer', 'Volunteer')], default='nurse', max_length=20, verbose_name='Caregiver role'),
        ),
    ]
