# Generated by Django 4.2.7 on 2023-11-26 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "activity type",
                "verbose_name_plural": "activity types",
                "db_table": "activity_type",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Activity date")),
                (
                    "duration_m",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Duration in minutes"
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="activities.activitytype",
                    ),
                ),
                (
                    "residents",
                    models.ManyToManyField(
                        related_name="activities", to="residents.resident"
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "db_table": "activity",
                "ordering": ["-date"],
            },
        ),
    ]
