# Generated by Django 4.2.7 on 2023-11-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("outdoor", "Outdoor"),
                    ("culture", "Culture"),
                    ("discussion", "Discussion"),
                    ("self_guided", "Self-guided"),
                ],
                default="self_guided",
                max_length=20,
                verbose_name="Activity type",
            ),
        ),
        migrations.DeleteModel(
            name="ActivityType",
        ),
    ]
