# Generated by Django 4.2.7 on 2023-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_rename_duration_m_activity_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="caregiver_role",
            field=models.CharField(
                choices=[
                    ("family", "Family"),
                    ("friend", "Friend"),
                    ("volunteer", "Volunteer"),
                    ("staff", "Staff"),
                    ("practical_nurse", "Practical nurse"),
                    ("nurse", "Nurse"),
                ],
                default="staff",
                max_length=20,
                verbose_name="Caregiver role",
            ),
        ),
    ]
