# Generated by Django 4.0.3 on 2022-04-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'home', 'verbose_name_plural': 'homes'},
        ),
        migrations.AlterModelTable(
            name='home',
            table='home',
        ),
    ]
