blank_issues_enabled: false

contact_links:
  - name: GeriLife Community Support
    url: https://github.com/GeriLife/caregiving/discussions
    about: Please ask and answer questions here.

  - name: Feature Requests
    url: https://github.com/GeriLife/caregiving/issues/new?template=feature_request.yml
    about: Have a feature you'd like to suggest? Please submit a feature request.

  - name: Bug Reports
    url: https://github.com/GeriLife/caregiving/issues/new?template=bug_report.yml
    about: Found a bug? Let us know by creating a bug report.
