# Generated by Django 4.0.3 on 2022-04-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caregiverrole',
            options={'verbose_name': 'caregiver role', 'verbose_name_plural': 'caregiver roles'},
        ),
        migrations.AlterModelTable(
            name='caregiverrole',
            table='caregiver_role',
        ),
    ]
