# Generated by Django 4.2.7 on 2023-12-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homes", "0003_home_url_uuid"),
        ("residents", "0003_resident_url_uuid"),
        ("activities", "0003_activity_caregiver_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("outdoor", "Outdoor"),
                            ("culture", "Culture"),
                            ("discussion", "Discussion"),
                            ("self_guided", "Self-guided"),
                        ],
                        default="self_guided",
                        max_length=20,
                        verbose_name="Activity type",
                    ),
                ),
                (
                    "activity_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Duration in minutes"
                    ),
                ),
                (
                    "caregiver_role",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("friend", "Friend"),
                            ("volunteer", "Volunteer"),
                            ("staff", "Staff"),
                            ("practical_nurse", "Practical nurse"),
                            ("nurse", "Nurse"),
                        ],
                        default="staff",
                        max_length=20,
                        verbose_name="Caregiver role",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activities.activity",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="homes.home"
                    ),
                ),
                (
                    "residency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="residents.residency",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="residents.resident",
                    ),
                ),
            ],
            options={
                "verbose_name": "resident_activity",
                "verbose_name_plural": "resident_activities",
                "db_table": "resident_activity",
            },
        ),
    ]
