# Generated by Django 5.0 on 2023-12-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('metrics', '0001_initial'), ('metrics', '0002_alter_residentactivity_activity_type_and_more'), ('metrics', '0003_residentactivity_activity_date'), ('metrics', '0004_alter_residentactivity_resident'), ('metrics', '0005_remove_residentactivity_activity'), ('metrics', '0006_residentactivity_group_activity_id')]

    initial = True

    dependencies = [
        ('activities', '0003_activity_caregiver_role'),
        ('homes', '0003_home_url_uuid'),
        ('residents', '0003_resident_url_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('outdoor', 'Outdoor'), ('casual_social', 'Casual Social'), ('culture', 'Culture'), ('discussion', 'Discussion'), ('guided', 'Guided'), ('music', 'Music'), ('self_guided', 'Self-guided'), ('trip', 'Trip')], default='self_guided', max_length=20, verbose_name='Activity type')),
                ('activity_minutes', models.PositiveIntegerField(default=30, verbose_name='Duration in minutes')),
                ('caregiver_role', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('hobby_instructor', 'Hobby Instructor'), ('nurse', 'Nurse'), ('physio_therapist', 'Physio therapist'), ('practical_nurse', 'Practical nurse'), ('volunteer', 'Volunteer')], default='nurse', max_length=20, verbose_name='Caregiver role')),
                ('home', models.ForeignKey(help_text='The home in which this activity was performed', on_delete=django.db.models.deletion.CASCADE, related_name='activity_performed', to='homes.home')),
                ('residency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='residents.residency')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_activities', to='residents.resident')),
                ('activity_date', models.DateField(null=True, verbose_name='Activity date')),
                ('group_activity_id', models.UUIDField(default=None, null=True, verbose_name='Group activity ID')),
            ],
            options={
                'verbose_name': 'resident_activity',
                'verbose_name_plural': 'resident_activities',
                'db_table': 'resident_activity',
            },
        ),
    ]
