# Generated by Django 4.2.8 on 2023-12-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_home_url_uuid'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentactivity',
            name='activity_type',
            field=models.CharField(choices=[('outdoor', 'Outdoor'), ('casual_social', 'Casual Social'), ('culture', 'Culture'), ('discussion', 'Discussion'), ('guided', 'Guided'), ('music', 'Music'), ('self_guided', 'Self-guided'), ('trip', 'Trip')], default='self_guided', max_length=20, verbose_name='Activity type'),
        ),
        migrations.AlterField(
            model_name='residentactivity',
            name='caregiver_role',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('hobby_instructor', 'Hobby Instructor'), ('nurse', 'Nurse'), ('physio_therapist', 'Physio therapist'), ('practical_nurse', 'Practical nurse'), ('volunteer', 'Volunteer')], default='nurse', max_length=20, verbose_name='Caregiver role'),
        ),
        migrations.AlterField(
            model_name='residentactivity',
            name='home',
            field=models.ForeignKey(help_text='The home in which this activity was performed', on_delete=django.db.models.deletion.CASCADE, related_name='activity_performed', to='homes.home'),
        ),
    ]
