# Generated by Django 5.0 on 2023-12-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_residentactivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentactivity',
            name='activity_date',
            field=models.DateField(null=True, verbose_name='Activity date'),
        ),
    ]
