# Generated by Django 5.0 on 2023-12-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_residentactivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentactivity',
            options={'verbose_name': 'resident activity', 'verbose_name_plural': 'resident activities'},
        ),
    ]
