# Generated by Django 5.0 on 2023-12-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_residentactivity_activity_date'),
        ('residents', '0003_resident_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentactivity',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_activities', to='residents.resident'),
        ),
    ]
