# Generated by Django 5.0 on 2023-12-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_residentactivity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentactivity',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
