# Generated by Django 5.0 on 2023-12-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_residentactivity_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentactivity',
            name='activity',
        ),
    ]
