# Generated by Django 5.0 on 2023-12-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_remove_residentactivity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentactivity',
            name='group_activity_id',
            field=models.UUIDField(default=None, null=True, verbose_name='Group activity ID'),
        ),
    ]
