# Generated by Django 4.2.7 on 2023-11-26 12:04

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0002_alter_resident_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="url_uuid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                length=22,
                max_length=22,
                prefix="",
                verbose_name="UUID used in URLs",
            ),
        ),
    ]
