# Generated by Django 5.0 on 2024-01-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_resident_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residency',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residencies', to='residents.resident'),
        ),
    ]
