# Generated by Django 4.0.3 on 2022-04-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_alter_home_options_alter_home_table'),
        ('caregivers', '0002_alter_caregiverrole_options_and_more'),
        ('work', '0002_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'work', 'verbose_name_plural': 'work'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'work type', 'verbose_name_plural': 'work types'},
        ),
        migrations.AlterField(
            model_name='work',
            name='caregiver_role',
            field=models.ForeignKey(help_text='The role or job title of the person who performed this work.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='caregivers.caregiverrole'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(help_text='The date this work was performed.'),
        ),
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.PositiveIntegerField(help_text='The number of minutes used performing this work.'),
        ),
        migrations.AlterField(
            model_name='work',
            name='home',
            field=models.ForeignKey(help_text='The home in which this work was performed.', on_delete=django.db.models.deletion.CASCADE, related_name='work_performed', to='homes.home'),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.ForeignKey(help_text='The general type of work performed.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='work.worktype'),
        ),
        migrations.AlterModelTable(
            name='work',
            table='work',
        ),
        migrations.AlterModelTable(
            name='worktype',
            table='work_type',
        ),
    ]
