# Generated by Django 4.0.6 on 2022-08-13 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_options_alter_worktype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='duration_hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(check=models.Q(('duration_hours__gte', 0.0)), name='work_duration_hours_gte_zero'),
        ),
    ]
