# Generated by Django 4.0.6 on 2022-08-13 10:10

from django.db import migrations

minutes_in_hour = 60

def add_duration_hours(apps, schema_editor):
    Work = apps.get_model("work", "Work")

    for work in Work.objects.all():
        work.duration_hours = work.duration / minutes_in_hour
        work.save()

def remove_duration_hours(apps, schema_editor):
    Work = apps.get_model("work", "Work")

    for work in Work.objects.all():
        work.duration_hours = 0
        work.save()

class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_work_duration_hours_and_more'),
    ]

    operations = [
        migrations.RunPython(add_duration_hours, remove_duration_hours,)
    ]
