# Generated by Django 4.0.6 on 2022-08-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20220813_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='duration',
            new_name='duration_minutes',
        ),
    ]
