# Generated by Django 4.2.8 on 2023-12-12 12:49

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_home_url_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('url_uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', verbose_name='UUID used in URLs')),
            ],
            options={
                'verbose_name': 'home group',
                'verbose_name_plural': 'home groups',
                'db_table': 'home_group',
            },
        ),
    ]
