# Generated by Django 4.2.8 on 2023-12-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_homegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='home_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homes', to='homes.homegroup'),
        ),
    ]
