# Generated by Django 4.2.8 on 2023-12-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_home_home_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homes', to='homes.homegroup'),
        ),
    ]
