# Generated by Django 4.0.4 on 2022-05-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'resident', 'verbose_name_plural': 'residents'},
        ),
        migrations.AlterModelTable(
            name='resident',
            table='resident',
        ),
    ]
