# Generated by Django 4.0.4 on 2022-05-23 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_resident_options_alter_resident_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
