# Generated by Django 4.0.4 on 2022-05-24 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_alter_home_options_alter_home_table'),
        ('residents', '0003_alter_resident_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in', models.DateField(default=django.utils.timezone.now)),
                ('move_out', models.DateField(blank=True, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homes.home')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='residents.resident')),
            ],
        ),
    ]
