# Generated by Django 4.0.4 on 2022-05-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_residency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residency',
            options={'verbose_name': 'residency', 'verbose_name_plural': 'residencies'},
        ),
        migrations.AlterModelTable(
            name='residency',
            table='residency',
        ),
    ]
